apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - slacker-statefulset.yaml
  - slacker-configmap.yaml

commonLabels:
  app.kubernetes.io/name: slacker
  app.kubernetes.io/component: bot
  app.kubernetes.io/part-of: marvin

namespace: marvin

images:
  - name: slacker
    newTag: latest