package conversation

import (
	"context"

	"github.com/ollama/ollama/api"
)

// Stats holds real-time statistics from LLM streaming responses
// Stats tracks token usage metrics for a single conversation.
type Stats struct {
	// PromptTokens is the number of tokens used for the user's input
	PromptTokens int

	// ResponseTokens is the number of tokens generated by the LLM
	ResponseTokens int

	// TotalTokens is the sum of prompt and response tokens
	TotalTokens int

	// EvalCount is the number of evaluations completed by the LLM
	EvalCount int

	// DoneReason indicates why the conversation turn completed
	DoneReason string

	// IsDone indicates if this is the final response (no more Tool calls expected)
	IsDone bool
}

// StreamingUpdater handles real-time output updates during conversations.
// It provides a unified interface for different backends (CLI, Slack, web UI) to receive
// content, thoughts, Tool calls, statistics, and flush notifications.
type StreamingUpdater interface {
	// AddContent streams regular conversation content to the output.
	// The content should be displayed immediately to provide real-time feedback.
	AddContent(ctx context.Context, content string) error

	// AddThought streams AI reasoning/thinking process.
	// This helps users understand the AI's decision-making process.
	AddThought(ctx context.Context, thought string) error

	// AddToolCall notifies when the AI invokes a Tool.
	// Provides transparency into Tool usage and execution.
	AddToolCall(ctx context.Context, toolCall api.ToolCall) error

	// AddToolResult notifies when a Tool execution completes with its result.
	// Provides visibility into Tool execution outcomes for debugging and user feedback.
	AddToolResult(ctx context.Context, toolCall api.ToolCall, result []api.Message, err error) error

	// UpdateStats provides real-time statistics about token usage and completion.
	// Enables monitoring, cost tracking, and performance analysis.
	UpdateStats(ctx context.Context, stats Stats) error

	// Flush signals completion of a conversation turn.
	// Allows backends to perform final cleanup and display.
	Flush(ctx context.Context) error
}

// OptionalStatisticsUpdater provides a default no-op implementation for UpdateStats
// This allows adapters that don't care about statistics to ignore them gracefully
type OptionalStatisticsUpdater struct {
	StreamingUpdater
}

// UpdateStats provides a default no-op implementation for UpdateStats.
func (o *OptionalStatisticsUpdater) UpdateStats(_ context.Context, _ Stats) error {
	// Default no-op implementation
	return nil
}

// WrapWithOptionalStats wraps a StreamingUpdater to provide no-op UpdateStats if not implemented
func WrapWithOptionalStats(updater StreamingUpdater) StreamingUpdater {
	if _, ok := updater.(interface {
		UpdateStats(ctx context.Context, stats Stats) error
	}); ok {
		return updater
	}
	return &OptionalStatisticsUpdater{StreamingUpdater: updater}
}
